# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rake"
gem "standalone_migrations"
gem "mysql2"
gem "pg"
gem "carmen"
gem "money"
